### ISSUE TITLE
使用docker的方式, 无法使用git

### ISSUE THREAD

**Issue by wweggplant** [sichang824/mcp-terminal#4]
是不是执行环境还是容器里, 不是server上的. 执行命令: docker run -p 8000:8000 mcp-terminal

**Comment by sichang824** [comment]
## 问题解释

这个问题涉及到 Docker 容器中访问服务器目录的正确方式。让我详细解释一下：

### 当前情况

- 使用 `docker run -p 8000:8000 mcp-terminal` 命令运行容器
- 程序在容器内执行，这是 Docker 的正常工作方式
- 容器是一个隔离的环境，默认情况下无法直接访问主机文件系统

### 解决方案：使用目录挂载（Volume Mount）

Docker 提供了目录挂载功能，可以让容器访问主机上的目录。有两种方式：

1. **使用 docker-compose（推荐）**
项目已经配置了 docker-compose.yml：

```yaml
services:
  mcp-terminal:
    build: .
    container_name: mcp-terminal
    volumes:
      - .:/workspace    # 将当前目录挂载到容器的 /workspace
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
```

使用方法：

```bash
docker-compose up
```

2. **直接使用 docker run**

```bash
docker run -v $(pwd):/workspace -p 8000:8000 mcp-terminal
```

### 目录挂载的好处

1. 容器内的 `/workspace` 目录与主机项目目录保持同步
2. 主机上的文件修改会立即反映到容器中
3. 容器内生成的文件会保存在主机上
4. 可以在主机上进行代码版本控制（git）

### 注意事项

1. 确保挂载的目录有适当的权限
2. 建议在主机上进行 git 操作，而不是在容器内
3. 如果需要在容器内使用 git，需要确保容器内安装了 git

### 验证方法

1. 在主机上修改文件，检查容器内是否同步更新
2. 在容器内创建文件，检查主机上是否可以看到
3. 确认 git 操作可以在主机上正常进行
